= Opciones de soporte comercial para Eclipse Temurin(TM)
:page-authors: gdams, tellison

Actualmente, hay disponible una variedad de opciones comerciales para el soporte de Eclipse Temurin. Es importante señalar que ninguno de estos proveedores ha sido evaluado ni cuenta con el respaldo oficial del proyecto Adoptium(R). Cada proveedor de soporte comercial tiende a atender diferentes casos de uso típicos, por lo que se recomienda que investigue cuidadosamente cada opción en función de sus necesidades y requisitos específicos.

En orden alfabético:

[cols="1,3"]
|===
| 
| 

^.^|
image:https://adoptium.net/images/openelements.svg[Open Elements,150]
|
Purchasing OpenElements Temurin Support & Care provides you with a variety of benefits that enhance the performance and security of your Java applications and optimize your development process. As a member of Adoptium and with our exceptional network within OpenElements, we directly contribute to its development. Through our activities in the Java and Open Source ecosystem, we can provide you with information and insights into the current and future developments within the Eclipse Adoptium Working Group and the OpenJDK.

For more details, please visit the https://open-elements.com/temurin-support/[Open Elements Website].

^.^|
image:https://adoptium.net/images/redhat.svg[Red Hat,150]
|
https://www.redhat.com[Red Hat] ha sido largamente reconocido por la comunidad Java, y continúa comprometido a llevar a Java, aún más allá, a través de una innovación potenciada por la comunidad abierta. Los clientes de Red Hat pueden obtener soporte profesional para Eclipse Temurin a través de una suscripción, la cual le permite acceder a un soporte 24x7 a nivel mundial para los sistemas críticos basados en Java.

Visite https://developers.redhat.com/java/red-hat-and-java?utm_source=adoptium[Red Hat & Java] o contáctenos https://www.redhat.com/contact?utm_source=adoptium[Red Hat Sales] para más información.

|===

Si eres un proveedor de Soporte Comercial para Eclipse Temurin y no estás en la lista, por favor https://github.com/adoptium/adoptium.net/issues/new/choose[ingresa a esta dirección] para ser agregado a la misma.
