= Archive Installation
:page-authors: gdams
:toc:

== Linux

. Make sure you have downloaded the latest link:/download[Linux binary]
to a directory that will not move or be deleted, and use Terminal to cd
into it.
. Optional: use these checksum instructions to ensure the authenticity
of your binary:
+
[source, bash]
----
# The command must in the same directory as the downloaded binary file
wget -O- -q -T 1 -t 1 <url_to_checksum_file> | sha256sum -c
----
+
. Extract the `.tar.gz.` You can use the following command:
+
[source, bash]
----
tar xzf <openjdk_binary>.tar.gz
----
+
. Add this version of Java to your `PATH`
+
[source, bash]
----
export PATH=$PWD/<extracted_directory>/bin:$PATH
----
+
. Check that Java has installed correctly:
+
[source, bash]
----
java -version
----

== macOS

. Make sure you have downloaded the latest link:/download[macOS binary]
to a directory that will not move or be deleted, and use Terminal to cd
into it.
. Optional: use these checksum instructions to ensure the authenticity
of your binary:
+
[source, bash]
----
# The command must in the same directory as the downloaded binary file
wget -O- -q -T 1 -t 1 <url_to_checksum_file> | sha256sum -c
----
+
. Extract the `.tar.gz.` You can use the following command:
+
[source, bash]
----
tar xzf <openjdk_binary>.tar.gz
----
+
. Add this version of Java to your `PATH`
+
[source, bash]
----
export PATH=$PWD/<extracted_directory>/Contents/Home/bin:$PATH
----
+
. Check that Java has installed correctly:
+
[source, bash]
----
java -version
----

== Windows

. Make sure you have downloaded the latest link:/download[Windows binary] to a directory that will not move or be deleted, and use Command
Prompt to cd into it.
. Optional: use these checksum instructions to ensure the authenticity
of your binary:
+
[source, powershell]
----
certutil -hashfile <downloaded_file>.zip SHA256
----
+
. Extract the .zip. You can use the following command:
+
[source, powershell]
----
Expand-Archive -Path .\<downloaded_file>.zip -DestinationPath .
----
+
. Add this version of Java to your `PATH`:
+
[source, powershell]
----
set PATH=%cd%\<extracted_directory>\bin;%PATH%
----
+
. Check that Java has installed correctly:
+
[source, powershell]
----
java -version
----

== AIX

. Make sure you have downloaded the latest link:/download[AIX binary]
to a directory that will not move or be deleted, and use Terminal to cd
into it.
. Optional: use these checksum instructions to ensure the authenticity
of your binary:
+
[source, bash]
----
# The command must in the same directory as the downloaded binary file
wget -O- -q -T 1 -t 1 <url_to_checksum_file> | sha256sum -c
----
+
. Extract the `.tar.gz.` You can use the following command:
+
[source, bash]
----
gunzip -c <openjdk_binary>.tar.gz | tar xf -
----
+
. Add this version of Java to your `PATH`
+
[source, bash]
----
export PATH=$PWD/<extracted_directory>/bin:$PATH
----
+
. Check that Java has installed correctly:
+
[source, bash]
----
java -version
----

== Solaris

. Make sure you have downloaded the latest link:/download[Solaris
binary] to a directory that will not move or be deleted, and use
Terminal to cd into it.
. Optional: use these checksum instructions to ensure the authenticity
of your binary:
+
[source, bash]
----
# The command must in the same directory as the downloaded binary file
wget -O- -q -T 1 -t 1 <url_to_checksum_file> | sha256sum -c
----
+
. Extract the `.tar.gz.` You can use the following command:
+
[source, bash]
----
gunzip -c <openjdk_binary>.tar.gz | tar xf -
----
+
. Add this version of Java to your `PATH`
+
[source, bash]
----
export PATH=$PWD/<extracted_directory>/bin:$PATH
----
+
. Check that Java has installed correctly:
+
[source, bash]
----
java -version
----
