= Linux (RPM/DEB) installer packages
:page-authors: gdams, karianna, perlun
:toc:
:icons: font

Eclipse Temurin RPM and DEB packages are now available for installing on
your favourite Linux distribution.

[NOTE]
====
See link:/supported-platforms[Supported Platforms] for a list of our officially supported installers by Linux distribution / version. Other Linux distributions / versions are supported on a best effort basis.
====

== Eclipse Temurin Package Names

The following name schema is being used:

....
temurin-<version>-jdk
e.g temurin-17-jdk or temurin-8-jdk
....

== Deb installation on Debian or Ubuntu

. Ensure the necessary packages are present:
+
[source, bash]
----
sudo apt-get install -y wget apt-transport-https gnupg
----
+
. Download the Eclipse Adoptium GPG key:
+
[source, bash]
----
wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo apt-key add -
----
+
. Configure the Eclipse Adoptium apt repository by replacing the values
in angle brackets:
+
[source, bash]
----
echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | sudo tee /etc/apt/sources.list.d/adoptium.list
----
+
. Install the Temurin version you require:
+
[source, bash]
----
sudo apt-get update # update if you haven't already
sudo apt-get install temurin-17-jdk
----

== CentOS/RHEL/Fedora Instructions

. Add the RPM repo to `/etc/yum.repos.d/adoptium.repo` making sure to
change the CentOS version if you are not using CentOS 8, and if you are
on a 32-bit ARM system, replace `$(uname -m)` with `armv7hl`. RPMs are
also available for RHEL and Fedora. To check the full list of versions
supported take a look at the list in the tree at
https://packages.adoptium.net/ui/repos/tree/General after clicking the
"Artifacts" link on the left.
+
[source, bash]
----
cat <<EOF > /etc/yum.repos.d/adoptium.repo
[Adoptium]
name=Adoptium
baseurl=https://packages.adoptium.net/artifactory/rpm/centos/8/$(uname -m)
enabled=1
gpgcheck=1
gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public
EOF
----
+
. Install the Temurin version you require:
+
[source, bash]
----
yum update # update if you haven't already
yum install temurin-17-jdk
----

== openSUSE/SLES Instructions

. Import the RPM repo making sure to change the openSUSE version if you
are not using OpenSUSE 15.2. RPM’s are also available for SLES 12 and 15. To check the full list of versions supported take a look at
https://packages.adoptium.net/ui/repos/tree/General/rpm.
+
[source, bash]
----
zypper ar -f https://packages.adoptium.net/artifactory/rpm/opensuse/15.2/$(uname -m) adoptium
----
+
. Install the Temurin version you require:
+
[source, bash]
----
zypper install temurin-17-jdk
----

Please raise any issues over at
https://github.com/adoptium/installer/issues.
