= Support
:page-authors: gdams, karianna, sxa, tellison, SueChaplain, sxa555, mvitz, ParkerM, M-Davies, Malax, lasombra, practicalli-john, jeffalder, hendrikebbers, douph1, andrew-m-leonard, mr-david-owens, DanHeidinga

== Community Support

Read https://medium.com/@javachampions/java-is-still-free-3-0-0-ocrt-2021-bca75c88d23b[Java Is Still Free (3.0.0)] for some background information about Java
support options. We are prepared to stand behind our release quality
binaries, so each build that is identified as a release receives support
via the Adoptium community. Our support means that you can
https://github.com/adoptium/adoptium-support/issues/new/choose[raise an
issue] to describe a bug you have found in the build, and we will work
with you and the appropriate development team to resolve it. Any fixes
we identify will be delivered as part of the next Adoptium release.

As a community of open source developers, our commitment is to triage
any issues raised and champion them in the appropriate source code
project. Of course, if the problem arises from the way we build and test
the code we can fix that directly. For dedicated support with service
level agreements you should contact commercial companies offering
support on Temurin binaries.

== Release Roadmap

The frequency of Adoptium releases is guided by the schedule of our
dependencies.

OpenJDK provide a new feature release every six months, and a
maintenance/security update based upon each active release every three
months. The release dates for those from the OpenJDK project are typically the
https://www.oracle.com/security-alerts/[Tuesdays closest to the 17th] of
January, April, July and October. We will follow this schedule for
publishing binary releases from Adoptium to ensure you get the latest,
most secure builds.

In addition, every two years since 2021 one feature release
will be designated as a Long Term Supported (LTS) release. We will
support LTS releases for at least four years. This assurance will allow
you to stay on a well-defined code stream, and give you time to migrate
to the next, new, stable, LTS release when it becomes available.

Based upon this roadmap, here is the timetable for the various OpenJDK
releases used to build Eclipse Temurin. Note that specific release dates
below are from the OpenJDK source project and may not match the date the
Adoptium project will have binaries available - there will usually be a
short delay while we complete our extensive build and tests cycles.

[width="100%",cols="5*",options="header",]
|===

| Java Version  | First Availability | Latest Release | Next Release Due | End of Availability ^[1]^

| Java 19
| Expected +
Sep 2022
| Not available
| Expected +
20 Sep 2022
| Expected Mar 2023

| Java 18
| Mar 2022
| 19 Apr 2022 +
[.small]#jdk-18.0.1+10#
| 19 Jul 2022 +
[.small]#jdk-18.0.2#
| Sep 2022

| Java 17 (LTS)
| Sep 2021
| 19 Apr 2022 +
[.small]#jdk-17.0.3+7#
| 19 Jul 2022 +
[.small]#jdk-17.0.4#
| At least Oct 2027

| Java 16
| Mar 2021
| 20 Jul 2021 +
[.small]#jdk-16.0.2+7#
| EOSL^[2]^
| Sep 2021

| Java 11 (LTS)
| Sep 2018
| 19 Apr 2022 +
[.small]#jdk-11.0.15+10#
| 19 Jul 2022 +
[.small]#jdk-11.0.16#
| At least Oct 2024

| Java 8 (LTS)
| Mar 2014
| 19 Apr 2022 +
[.small]#jdk8u332#
| 19 Jul 2022 +
[.small]#jdk8u342#
| At least Nov 2026

|===

^[1]^ As a general philosophy, Adoptium will continue to build binaries
for LTS releases as long as the corresponding upstream source is
actively maintained.

^[2]^ End of Service/Support Life - this code stream is no longer being
maintained. No further builds of Eclipse Temurin are planned.
